add normalize.css + some some styling fixes
martynasj/coin-portfolio pull request #16
Opened 2018-01-18 22:45 UTC by ignasBa

2018-01-19 08:36 UTC, martynasj requested changes

2018-01-19 08:36 UTC, martynasj commented on src/assets/index.html
> +    <link rel="stylesheet" type="text/css" href="/assets/normalize.css">
neaisku kur hostinsim ir kaip ta appsa, tai gal geriau importink per js ta css faila?

2018-01-19 11:45 UTC, ignasBa commented on src/assets/index.html
> +    <link rel="stylesheet" type="text/css" href="/assets/normalize.css">
bet tai ta dalis `/assets/nomalize.css` tai nesikeis nuo hostinimo, ne?

2018-01-20 10:32 UTC, martynasj commented on src/assets/index.html
> +    <link rel="stylesheet" type="text/css" href="/assets/normalize.css">
gali keistis jei index.html fails atsidurtu pvz shitcoin.com/app/

2018-01-20 20:15 UTC, martynasj approved these changes

2018-01-20 20:15 UTC, merged