add temp favicon and logo
martynasj/coin-portfolio pull request #30
Opened 2018-02-07 22:29 UTC by ignasBa

2018-02-07 23:23 UTC, martynasj requested changes

2018-02-07 23:23 UTC, martynasj commented on src/app/containers/PortfolioView/PortfolioView.tsx
> +          <link rel="icon" type="image/png" href={fav16} />
o home page nebus favicon? 😢

2018-02-08 18:18 UTC, ignasBa commented on src/app/containers/PortfolioView/PortfolioView.tsx
> +          <link rel="icon" type="image/png" href={fav16} />
oh

2018-02-08 18:30 UTC, ignasBa commented on src/app/containers/PortfolioView/PortfolioView.tsx
> +          <link rel="icon" type="image/png" href={fav16} />
patvarkiau

2018-02-08 18:37 UTC, martynasj approved these changes

2018-02-08 18:37 UTC, merged